server:
  port: 8010

spring:
  application:
    name: cloud-consumer-user


logging:
  level:
    root:info

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

